# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SlideMenuControllerSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SlideMenuControllerSwift
  pod 'Alamofire', '~> 4.2'
  pod 'SwiftyJSON', '~> 3.1'
  pod 'SwiftSpinner', '~> 1.1'

  target 'SlideMenuControllerSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SlideMenuControllerSwift-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SlideMenuControllerSwift-iOS

end
