# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CongressSearchEngine' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CongressSearchEngine
  pod 'SlideMenuControllerSwift'
  
  target 'CongressSearchEngineTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CongressSearchEngineUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
